import { UploadKind, UploadPanelConfig } from './models/upload.models';

export const uploadPanelConfigs: Record<UploadKind, UploadPanelConfig> = {
  orders: {
    kind: 'orders',
    title: 'Ordini',
    endpointLabel: '/orders/ingest/batch',
    chooseLabel: 'Seleziona PDF',
    uploadLabel: 'Invia ordini',
    accept: '.pdf,application/pdf',
    invalidFileTypeMessageDetail: 'Carica solo PDF.',
    maxFileSize: 20_000_000,
    emptyTitle: 'Trascina qui gli ordini',
    emptyDescription: '',
    icon: 'pi-file-pdf',
    iconClass: 'text-teal-700',
  },
  invoices: {
    kind: 'invoices',
    title: 'Fatture',
    endpointLabel: '/invoices/ingest/batch',
    chooseLabel: 'Seleziona PDF',
    uploadLabel: 'Invia fatture',
    accept: '.pdf,application/pdf',
    invalidFileTypeMessageDetail: 'Carica solo PDF.',
    maxFileSize: 20_000_000,
    emptyTitle: 'Trascina qui le fatture',
    emptyDescription: '',
    icon: 'pi-receipt',
    iconClass: 'text-cyan-700',
  },
  'paid-order-items': {
    kind: 'paid-order-items',
    title: 'Pagamenti',
    endpointLabel: '/paid-order-items/ingest',
    chooseLabel: 'Seleziona XLSX',
    uploadLabel: 'Invia pagamenti',
    accept: '.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    invalidFileTypeMessageDetail: 'Carica solo XLSX.',
    maxFileSize: 30_000_000,
    emptyTitle: 'Trascina qui i pagamenti',
    emptyDescription: '',
    icon: 'pi-file-excel',
    iconClass: 'text-emerald-700',
  },
};
